[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

[dependencies]
cuda_std = { version = "0.2", path = "/home/kdcadet/code/Rust-CUDA/crates/cuda_std" }

[lib]
crate-type = ["cdylib", "rlib"]
